name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[d]'
          python -m pip install tox

      - name: Run pre-commit hooks
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files
